### ISSUE TITLE
Make a logger specifically for builds

### ISSUE THREAD

**Issue by sebastianmonten** [KTH-DD2480-Fundsoft/assignment-2#16]
Description: In `ci_server/logger.py` the _Logger_ class is for general logging, but the builds should have a Logger class that just focuses on the data related to builds: ref, commitID, commit timestamp, commit author and pusher. Create a module for this in a subdirectory called `build_history`. Checkout `add new handler`. 

Definition of done: The module described above is implemented and merged to main.

**Comment by dantevi** [comment]
What is this about?
