### ISSUE TITLE
Investigate web interface for displaying build history

### ISSUE THREAD

**Issue by sebastianmonten** [KTH-DD2480-Fundsoft/assignment-2#22]
Description: Each build is given a unique URL, that is accessible to get the build information (commit identifier, build date, build logs). One URL exists to list all builds. This is part of the P+ requirements. 

Definition of done: A clear idea of how to implement a working web interface that lists the last builds and allows user to click them and get the build information (commit identifier, build date, build logs).

**Comment by Stenmarken** [comment]
I've decided to use the package flask_autoindex to do this which has a method AutoIndex that handles the front end and url part. Each file in a specified local directory gets a url and the file contents are displayed when the file is clicked on. The file contents then show the commit ID, build date, and the build logs. See #39 for the actual implementation.
