### ISSUE TITLE
FileNotFoundError when running ci_logic.py

### ISSUE THREAD

**Issue by sebastianmonten** [KTH-DD2480-Fundsoft/assignment-2#26]
Description: `ci_logic` doesn't seem to find the directory /tmp/log. My guess it that we first have to make sure it exists before attempting to write to a file there. According the error messages from running `python3 ci_server/ci_logic.py` from root folder, the error occurs in `test_logger.py`. 

Definition of done: Locate and fix the bug.

**Comment by sebastianmonten** [comment]
This is probably because the versions of the project that is currently cloned into the `/tmp` folder does not contain `/log`and `/build_history`. Should we add these to our repo so that we can run the tests?

**Comment by dantevi** [comment]
We should have a check to see if they exist (which they won't when cloning) and create the directories if they don't exist. Right?

**Comment by dantevi** [comment]
Now I noticed that this bug is also the exact same to #32 I think
