### ISSUE TITLE
Implement unique URL for each build (Related to task `P7`)

### ISSUE THREAD

**Issue by sebastianmonten** [KTH-DD2480-Fundsoft/assignment-2#27]
~~Description: If each build in `/build_history` is logged in its own file, it is straightforward to implement the listing of previous builds in the browser.~~

## Description:
According to task `P7` in the assignment specification, the CI server needs to the following:

1. Keep the history of the past builds*"
2. This history persists even if the server is rebooted*"
3. Each build is given a unique URL, that is accessible to get the build information (commit identifier, build date, build logs)
4. One URL exists to list all builds.

## Definition of done
The first and second parts are already handled by the `ci_server`. This issue will be about implementing the third part. The fourth part is solved by issue #39.

A file is created for each build where each file is named with the full time stamp, for example:

`build_2024-02-09_14-15-23-866.txt` (YYYY-MM-DD_HH-MM-SS-sss)

Each build gets a unique txt file in `build_history/`, tests are implemented and the change is pushed and then merged to main.

## Testing
Test that the correct file is created when a new build is logged.

**Comment by dantevi** [comment]
I have a suggestion regarding the build logging file name format. We could simplify by writing something like this:

`{yyymmdd}-{hhmmss}-{commit-id}`

for example:

`20240212-133542-dasdafasa`

Not sure how the `commit-id` should look like though. Maybe it should only be a substring?

**Comment by dantevi** [comment]
Also, maybe the assignment specification allows us to simply access the build history through a txt file instead of implementing a nicer HTML view? Since it seems to be possible to display the content of txt file via http with the server.
