### ISSUE TITLE
Use unittest module to run the CI tests in test_runner

### ISSUE THREAD

**Issue by rasmus-d** [KTH-DD2480-Fundsoft/assignment-2#29]
Description: The current way of running a subprocess is messy and requires that we redirect stdout and have no easy way to get error messages. Go back to using the unittest module directly. The current solution is unstable depending on the dev environment and causes bugs.

DoD: The run_test module works as intended using the unittest module. Merged to main.

**Comment by Stenmarken** [comment]
We tried to go back to the old way but that caused annoying import problems. We have decided to stick with the subprocess approach now.
