### ISSUE TITLE
Implement static syntax check

### ISSUE THREAD

**Issue by dantevi** [KTH-DD2480-Fundsoft/assignment-2#36]
## Description
According to task `P1` in the assignment specification, the CI needs to perform a "static syntax check" "for languages without compiler".
It is not entirely clear what this means so the *definition of done* needs a conclusive understanding in order to be written.

## Definition of done
Needs further discussion.

**Comment by Stenmarken** [comment]
Isn't this already implemented in test_compilation.py? Here we compile all the files in ci_server which is a way of checking the syntax.

**Comment by dantevi** [comment]
Yes, it seems this is what they are asking for. I opened this issue before realising that it was already implemented, which @rasmus-d clarified to me.

I'll close it due to this.
