### ISSUE TITLE
Error occurs when running server and sending a webhook payload - 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by sebastianmonten** [KTH-DD2480-Fundsoft/assignment-2#40]
Description: 

From `server.py`:
```
    authkey = app.config["AUTHKEY"] 
    # Make sure the authkey is correct.
    authorized = "X-Hub-Signature-256" in request.headers 
    authorized = authorized and request.headers["X-Hub-Signature-256"] == authkey 
    if not authorized:
        log.error(f"Invalid secret key from {request.remote_addr}")
        return UNAUTHORIZED
 ```
The key from discord does not work. I may have misunderstood how to use it.

**Comment by rasmus-d** [comment]
Im not sure that GH doesn't wrap the key in something or that I missed some whitespace when generating the checksum. Put a print statement `print(request.headers["X-Hub-Signature-256"])` and check for yourself.
